version: '3.8'

services:
  # API Gateway (Kong)
  api-gateway:
    image: kong:3.4
    container_name: fittracker-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8080  # ← CHANGED FROM 8001 to 8080
    volumes:
      - ./infrastructure/kong.yml:/kong/declarative/kong.yml
    ports:
      - "8000:8000"   # Proxy port (main API gateway)
      - "8080:8080"   # Admin API (changed from 8001 to 8080)
    depends_on:
      - user-service
      - workout-service
      - exercise-service
      - progress-service
      - ai-coach-service
  # User Service
  user-service:
    build: ./services/user-service
    container_name: fittracker-user-service
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
    ports:
      - "8001:8000"
    volumes:
      - ./services/user-service:/app
    restart: unless-stopped

  # Workout Service  
  workout-service:
    build: ./services/workout-service
    container_name: fittracker-workout-service
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
    ports:
      - "8002:8000"
    volumes:
      - ./services/workout-service:/app
    restart: unless-stopped

  # Exercise Service
  exercise-service:
    build: ./services/exercise-service
    container_name: fittracker-exercise-service
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
    ports:
      - "8003:8000"
    volumes:
      - ./services/exercise-service:/app
    restart: unless-stopped

  # Progress Service
  progress-service:
    build: ./services/progress-service
    container_name: fittracker-progress-service
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
    ports:
      - "8004:8000"
    volumes:
      - ./services/progress-service:/app
    restart: unless-stopped

  # AI Coach Service
  ai-coach-service:
    build: ./services/ai-coach-service
    container_name: fittracker-ai-coach-service
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8000
    ports:
      - "8005:8000"
    volumes:
      - ./services/ai-coach-service:/app
    restart: unless-stopped

  # Redis for caching and message queues
  redis:
    image: redis:7-alpine
    container_name: fittracker-redis
    ports:
      - "6379:6379"
    restart: unless-stopped